replicaCount: 1

image:
  repository: dahalsujata52897/webapp
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

namespace: eshop

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    # cpu: 250m
    # memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  CallBackUrl: "https://webapp.eshop.svc.cluster.local"
  HTTP_PORTS: "8080"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  IdentityUrl: "https://identity-api.eshop.svc.cluster.local"
  services__basket-api__http__0: "http://basket-api:8080"
  services__catalog-api__http__0: "http://catalog-api:8080"
  services__ordering-api__http__0: "http://ordering-api.eshop.svc.cluster.local"
  TrustServerCertificate: "true"
        
volumeMounts:

volumes: 

secretStore:
  secretName: kv-secrets