apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
